apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: LoadBalancer
  ports:
    - name: react
      port: 3000
      targetPort: 3000
  selector:
    app: frontend