apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  namespace: database
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 400Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data