apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  selector:
    app: database
             