apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: LoadBalancer
  ports:
    - name: django
      port: 8000
      targetPort: 8000
  selector:
    app: backend